install.packages("plyr")
library(plyr)
summary(EastWestAirlines)
str(EastWestAirlines)
mydata <- scale(EastWestAirlines [,2:12])
plot(mydata)
wss <- c()
for (i in 2:12) wss[i] <- sum(kmeans(mydata, centers = i)$withinss)
plot(1:12, wss, type = "b", xlab = "No. of clusters", ylab = "Avg Distance")
fit <- kmeans(mydata,3)
finalmodel <- data.frame(mydata,fit$cluster)
